name: Deploy to Test Environment

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "develop"

jobs:
  deploy-test:
    uses: ./.github/workflows/deploy-steps.yml
    with:
      environment: test
    secrets:
      AZURE_FUNCTIONAPP_PUBLISH_PROFILE: ${{ secrets.TEST_AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
      AZURE_FUNCTIONAPP_NAME: ${{ secrets.TEST_AZURE_FUNCTIONAPP_NAME }}
